import { ChatResponse, ResponseMeta, EvidenceSource } from '../types/api';

// ============================================================
// PHASE 1 DEMO: builds structured metadata for a bot reply.
// Real backend fields are used when present; everything else is
// PREVIEW data so the UI structure can be demoed before RAG (Phase 2),
// confidence (Phase 3) and XAI (Phase 4) exist.
// Replace this with a pass-through once the backend returns them.
// ============================================================

// ---- OLD topic-specific samples (always showed cold/fever, whatever was asked) ----
// const MOCK_SOURCES = [
//   { title: 'Common Cold — Symptoms and Self-Care', publisher: 'MedlinePlus (NIH)', url: 'https://medlineplus.gov/commoncold.html', snippet: 'Rest, fluids and over-the-counter remedies relieve most symptoms.' },
//   { title: 'Fever: First Aid', publisher: 'Mayo Clinic', url: 'https://www.mayoclinic.org/first-aid/first-aid-fever/basics/art-20056685', snippet: 'Seek care if fever exceeds 103°F (39.4°C) or lasts more than 3 days.' },
//   { title: 'Self-care for minor illness', publisher: 'NHS', url: 'https://www.nhs.uk/', snippet: 'Many minor illnesses can be managed at home with simple measures.' },
// ];
// const MOCK_EXPLANATION = [
//   'Matched your symptoms to common, low-risk conditions.',
//   'Prioritised widely recommended self-care before medication.',
//   'Added warning signs that should prompt a doctor visit.',
// ];

// Generic, real reference libraries — true for any question, no invented quotes.
// (Not per-answer citations: those arrive with RAG in Phase 2.)
const GENERIC_SOURCES: EvidenceSource[] = [
  {
    title: 'MedlinePlus — Health Topics',
    publisher: 'U.S. National Library of Medicine (NIH)',
    url: 'https://medlineplus.gov/healthtopics.html',
    snippet: 'Trusted consumer information on conditions, symptoms, medicines and tests.',
  },
  {
    title: 'Health A to Z',
    publisher: 'NHS (UK National Health Service)',
    url: 'https://www.nhs.uk/conditions/',
    snippet: 'Plain-language guidance on symptoms, self-care and when to get help.',
  },
  {
    title: 'Health Topics',
    publisher: 'World Health Organization (WHO)',
    url: 'https://www.who.int/health-topics',
    snippet: 'Global public-health guidance and fact sheets.',
  },
];

// Spanish-speaking users get MedlinePlus en español instead of the English library
const MEDLINEPLUS_ES: EvidenceSource = {
  title: 'MedlinePlus en español — Temas de salud',
  publisher: 'Biblioteca Nacional de Medicina de EE. UU. (NIH)',
  url: 'https://medlineplus.gov/spanish/healthtopics.html',
  snippet: 'Información confiable sobre enfermedades, síntomas, medicamentos y pruebas.',
};

const sourcesFor = (language?: string): EvidenceSource[] =>
  language === 'ES' ? [MEDLINEPLUS_ES, ...GENERIC_SOURCES.slice(1)] : GENERIC_SOURCES;

// Describes how answers are actually produced today — accurate for every reply.
const GENERIC_EXPLANATION = [
  'Answer generated by the CURA-X medical language model from general medical knowledge.',
  'Focused on your question, using earlier messages in this conversation for context.',
  'Includes warning signs that need a doctor when they are relevant.',
  'General information only — not a diagnosis or a personal medical plan.',
];

export const buildResponseMeta = (data: ChatResponse, language: string): ResponseMeta => {
  // Backend currently hardcodes confidence = 1.0 (placeholder), so treat that as "not real".
  const hasRealConfidence = typeof data.confidence === 'number' && data.confidence < 1;
  const hasSources = Array.isArray(data.sources) && data.sources.length > 0;
  const hasExplanation = Array.isArray(data.explanation) && data.explanation.length > 0;
  const lang = data.language ?? language;

  return {
    confidence: hasRealConfidence ? data.confidence! : 0.78 + Math.random() * 0.15,
    sources: hasSources ? data.sources! : sourcesFor(lang),
    explanation: hasExplanation ? data.explanation! : GENERIC_EXPLANATION,
    // Emergency detection is NOT implemented yet — only shown if backend sends it.
    emergency: data.emergency ?? null,
    language: lang,
    isMock: !(hasRealConfidence && hasSources && hasExplanation),
  };
};

// Saved replies from before this change still carry the old cold/fever samples.
// When a conversation is loaded, swap any preview data for the current generic set.
export const refreshPreviewMeta = (meta?: ResponseMeta): ResponseMeta | undefined =>
  meta && meta.isMock
    ? { ...meta, sources: sourcesFor(meta.language), explanation: GENERIC_EXPLANATION }
    : meta;
